sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  wechat:
    appid:
    secret:
    # 传智商务号
    mchid:
    # 对应的证书的序列号
    mchSerialNo:
    #    privateKeyFilePath: D:\apiclient_key.pem 私钥文件
    # 解密密钥(商户平台设置)
    apiV3Key:
    #    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem 平台证书
    # 支付成功回调 内网穿透临时域名+/notify/paySuccess(Controller层接口)
    notifyUrl:
    # 退款成功回调 内网穿透临时域名+/notify/refundSuccess(Controller层接口)
    refundNotifyUrl:
  alioss:
      endpoint:
      access-key-id:
      access-key-secret:
      bucket-name:
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak:
  redis:
    host: 192.168.42.129
    port: 6379
    password: 123456
    database: 0
    timeout: 5000ms
