sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  wechat:
    appid:
    secret:
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host: 192.168.42.129
    port: 6379
    password: 123456
    database: 0
    timeout: 5000ms
